databases:
  - name: sga_db
    databaseName: sga_db
    user: sga_user
    plan: free # Hobby Plan

services:
  - type: web
    name: sga_web
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p 8000 SGA.asgi:application"
    plan: free # Hobby Plan
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: sga_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "sga-c3f2.onrender.com" # Ajuste conforme necessário após deploy
